### ISSUE TITLE
网站崩溃了！

### ISSUE THREAD

**Issue by penggang-home** [ppzreboot/k-colors.js#1]
我上传了一张6.1M的图片，然后...
<img width="841" alt="image" src="https://github.com/user-attachments/assets/accfd413-af9b-4374-a40a-46b3ed33acac">

原图：
![紫幻](https://github.com/user-attachments/assets/c90e19d9-de6d-47a7-9337-8bb6c4fb6afd)

**Comment by ppzreboot** [comment]
昨天添加这个功能时，我就发现这个问题了，但是我以为没人用，就没改嘿嘿嘿

原来是内存炸了（可能是递归导致的，我也不太懂，反正改成循环就好了）

感谢提醒！！！

（图真好看）
![clustered (1)](https://github.com/user-attachments/assets/fa70776f-3caf-4257-a365-566c369903cf)

**Comment by ppzreboot** [comment]
这位二次元老婆叫啥啊
